In [1]:
import numpy as np


In [2]:
arr_1d = np.array([1,22,33,44])
print("1D Array:",arr_1d)

1D Array: [ 1 22 33 44]


In [3]:
arr_2d = np.array([[11,2,32],[4,54,6]])
print("2D Array:\n",arr_2d)

2D Array:
 [[11  2 32]
 [ 4 54  6]]


In [4]:
arr_3d = np.array([[[12,22,3],[4,53,6]],[[17,18,19],[10,11,12]]])
print("3D Array:\n\n",arr_3d)

3D Array:

 [[[12 22  3]
  [ 4 53  6]]

 [[17 18 19]
  [10 11 12]]]


In [6]:
import numpy as np
random_data = np.random.normal(loc=0, scale=1, size=100)

In [7]:
random_data

array([-0.7200538 ,  1.10705659,  0.58804387,  0.82307857,  0.5078925 ,
       -0.025898  , -0.23748778, -0.28752958, -0.80174081,  1.44563718,
        0.03508352,  0.37407907,  0.49538622,  0.57360781, -0.44334835,
       -0.50270813, -1.26576951,  0.31212277, -0.19688416,  0.36089468,
       -2.72324719, -0.94363757,  0.81084348,  0.3983313 ,  1.35929388,
       -1.71129508, -0.75304538,  1.38802281,  1.2487923 ,  0.46058339,
       -1.46109141,  1.41748265, -0.21269265, -0.58357523, -0.49182346,
        1.49115256, -0.01772249, -0.28810691, -0.25366353,  0.71562246,
        0.71083886,  0.6753823 , -1.27359611,  0.73991512,  0.84483377,
        0.193669  ,  0.27999752, -0.2839314 , -0.32926702,  1.26792169,
        0.22306622,  0.47322066, -0.60059826, -0.79892133,  0.96278168,
       -0.62569669, -1.40065173,  0.25662687,  2.37769951, -1.59183855,
       -0.33875107, -0.50678237, -0.56705197, -1.46960693, -1.0705021 ,
       -2.30582485,  0.35134729,  1.70395844, -0.34067134,  0.02

In [8]:
linear_data = np.linspace(0, 10, 50)

In [9]:
linear_data

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [11]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xx, yy = np.meshgrid(x, y)

grid_dataset = np.column_stack((xx.ravel(), yy.ravel()))

In [12]:
grid_dataset

array([[-5.        , -5.        ],
       [-3.88888889, -5.        ],
       [-2.77777778, -5.        ],
       [-1.66666667, -5.        ],
       [-0.55555556, -5.        ],
       [ 0.55555556, -5.        ],
       [ 1.66666667, -5.        ],
       [ 2.77777778, -5.        ],
       [ 3.88888889, -5.        ],
       [ 5.        , -5.        ],
       [-5.        , -3.88888889],
       [-3.88888889, -3.88888889],
       [-2.77777778, -3.88888889],
       [-1.66666667, -3.88888889],
       [-0.55555556, -3.88888889],
       [ 0.55555556, -3.88888889],
       [ 1.66666667, -3.88888889],
       [ 2.77777778, -3.88888889],
       [ 3.88888889, -3.88888889],
       [ 5.        , -3.88888889],
       [-5.        , -2.77777778],
       [-3.88888889, -2.77777778],
       [-2.77777778, -2.77777778],
       [-1.66666667, -2.77777778],
       [-0.55555556, -2.77777778],
       [ 0.55555556, -2.77777778],
       [ 1.66666667, -2.77777778],
       [ 2.77777778, -2.77777778],
       [ 3.88888889,

In [13]:
print("Array Properties\n")
print("Shape:",arr_2d.shape)
print("Size:",arr_2d.size)
print("Data Type:",arr_2d.dtype)

Array Properties

Shape: (2, 3)
Size: 6
Data Type: int64


In [14]:
zeros=np.zeros((2,3))
print("Zeros array:\n",zeros)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
ones=np.ones((3,6))
print("Zeros array:\n",ones)

Zeros array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
identity=np.eye(4)
print("Identity Matrix:\n",identity)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
linespace=np.linspace(0,10,3)
print("Linespace:\n",linespace)

Linespace:
 [ 0.  5. 10.]


In [18]:
arrange_array=np.arange(0,100,2)
print("Arranging:\n",arrange_array)

Arranging:
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [19]:
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
add = array_a +array_b
print("Addition:\n",add)

Addition:
 [5 7 9]


In [20]:
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
mul = array_a * array_b
print("Multiplication:\n",mul)

Multiplication:
 [ 4 10 18]


In [21]:
scalar_multiply = array_a * 2
print("Scalar Multiplication:\n",scalar_multiply)

Scalar Multiplication:
 [2 4 6]


In [22]:
matrix_a=([1,2],[11,12])
matrix_b=([4,5],[14,15])
mul = np.dot(matrix_a,matrix_b)
print("Matrix Multiplication:\n",mul)

Matrix Multiplication:
 [[ 32  35]
 [212 235]]


In [23]:
array = np.array([10,20,30,40])
print("Array:\n",array)

Array:
 [10 20 30 40]


In [24]:
print("Elements at index 1: ",array[1])
print("Elements at index 1 to 3: ",array[2:4])

Elements at index 1:  20
Elements at index 1 to 3:  [30 40]


In [25]:
large_array = np.array([1,2,3,4,5,6,7,8,9])
print("Statistical Operations:\n")
print("Sum:",large_array.sum())
print("Mean:",large_array.mean())
print("Standard Deviation:",large_array.std())
print("Max:",large_array.max())
print("Min:",large_array.min())

Statistical Operations:

Sum: 45
Mean: 5.0
Standard Deviation: 2.581988897471611
Max: 9
Min: 1


In [26]:
reshaped = large_array.reshape(3,3)
print("Reshaped Array:\n",reshaped)

Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
r=reshaped.flatten()
print(r)

[1 2 3 4 5 6 7 8 9]


In [28]:
random_array= np.random.random((2,3))
print("Random array:\n",random_array)

Random array:
 [[0.90454426 0.79891505 0.22080413]
 [0.31625565 0.51884186 0.86649643]]


In [29]:
random_int= np.random.randint(1,10,size=(2,3))
print("Random Integers:\n",random_int)

Random Integers:
 [[2 6 6]
 [8 9 7]]
